### PR TITLE
Adding sendTag and sendTags OneSignal Methods.

### PR DESCRIPTION
**Pull request by slothluvchunk**
Follows the same structure of other native OneSignal methods like sendEmail, implementing the sendTag and sendTags methods. 
This allows the ability to set a single tag, or a collection of tags for audience segmenting and filtering within the OneSignal console.
Documentation on sendTag(s):
https://documentation.onesignal.com/docs/web-push-sdk#sendtag

### CODE REVIEW

**Comment by pedro-lb** [comment]
Hey there @slothluvchunk !

There are some conflicts due to the previous pull request.

Can you please fix them? I'll merge it as soon as that's done :)

**Comment by slothluvchunk** [comment]
@pedro-lb  - Should be good to go, but don't hesitate to let me know if anything else is needed. Thanks! :)

**Comment by pedro-lb** [comment]
Looks good!

I've created another PR to fix rebase issues - code will be merged into `master` there.

**Comment by pedro-lb** [comment]
Released in https://github.com/pedro-lb/react-onesignal/releases/tag/1.3.0

**Pull request closed without merging**
